builds:
  - main: ./cmd/gtag
    binary: gtag
    env:
      - CGO_ENABLED=0
    # ldflags:
    #   - -X 'main.ProgramVersion={{.Version}}'
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  disable: true
brews:
  - repository:
      owner: chebread
      name: homebrew-gtag
      branch: master
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    homepage: "https://github.com/chebread/gtag"
    description: "Automate your Git tagging workflow."
    license: "MIT"

    install: |
      bin.install "gtag"
